const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('plano', {
  saveProject: (project, saveAs = false) => ipcRenderer.invoke('project:save', project, saveAs),
  activateProject: filePath => ipcRenderer.invoke('project:activate', filePath),
  updateDocumentState: state => ipcRenderer.invoke('project:state', state),
  listRecentPlans: () => ipcRenderer.invoke('project:recent-list'),
  openRecentPlan: filePath => ipcRenderer.invoke('project:recent-open', filePath),
  removeRecentPlan: filePath => ipcRenderer.invoke('project:recent-remove', filePath),
  openProject: () => ipcRenderer.invoke('project:open'),
  initialProject: () => ipcRenderer.invoke('project:initial'),
  exportPDF: payload => ipcRenderer.invoke('export:pdf', payload),
  exportImage: payload => ipcRenderer.invoke('export:image', payload),
  searchOpenFoodFacts: request => ipcRenderer.invoke('open-food-facts:search', request),
  openOpenFoodFactsProduct: code => ipcRenderer.invoke('open-food-facts:open', code),
  onCloseRequest: callback => { const listener = () => callback(); ipcRenderer.on('app:closing', listener); return () => ipcRenderer.removeListener('app:closing', listener); },
  onProjectRequested: callback => { const listener = (_, project) => callback(project); ipcRenderer.on('project:requested', listener); return () => ipcRenderer.removeListener('project:requested', listener); },
  onMenuAction: callback => { const listener = (_, action) => callback(action); ipcRenderer.on('menu:action', listener); return () => ipcRenderer.removeListener('menu:action', listener); },
  updateMenuState: state => ipcRenderer.invoke('menu:update', state),
  finishClose: () => ipcRenderer.send('app:close-ready'),
});
