import { useState } from 'react';
import { Check, Layers, Plus } from 'lucide-react';
import { Modal } from './Modal';
import { capacity, getGroups, mergeGroups, uid, validBlock } from './domain';
import { percent, salesText } from './format';
import type { Project } from './types';
function Members({ p, value, onChange }: { p: Project; value: string[]; onChange: (ids: string[]) => void }) {
  const groups = getGroups(p).filter(g => !g.id.startsWith('custom-'));
  const [search, setSearch] = useState('');
  return <div className="members"><input className="member-search" aria-label="Rechercher un groupe" placeholder="Rechercher un groupe à inclure…" value={search} onChange={e => setSearch(e.target.value)}/><div className="member-list">{groups.filter(g => g.label.toLowerCase().includes(search.toLowerCase())).map(g => <label key={g.id}><input type="checkbox" checked={value.includes(g.id)} onChange={e => onChange(e.target.checked ? [...value, g.id] : value.filter(id => id !== g.id))}/><i style={{ background: g.color }}/><span>{g.label}</span><small>{percent(g.share)}</small></label>)}</div><div className="member-total">{value.length} groupes sélectionnés<strong>{salesText(groups.filter(g => value.includes(g.id)).reduce((sum, g) => sum + g.sales, 0), p.salesMetric)}</strong></div></div>;
}
export function GroupDialog({ p, onClose, onCreate }: { p: Project; onClose: () => void; onCreate: (p: Project) => void }) {
  const [name, setName] = useState(''), [color, setColor] = useState('#2764cf'), [members, setMembers] = useState<string[]>([]);
  return <Modal title="Créer un regroupement" subtitle="Les ventes sont additionnées. Les implantations existantes sont conservées." onClose={onClose}><div className="dialog-body"><label className="field">Nom du regroupement<input placeholder="Ex. Autres marques" value={name} onChange={e => setName(e.target.value)}/></label><label className="color-field"><input type="color" aria-label="Couleur du regroupement" value={color} onChange={e => setColor(e.target.value)}/><span>Couleur du regroupement</span></label><Members p={p} value={members} onChange={setMembers}/></div><div className="modal-footer"><button className="button" onClick={onClose}>Annuler</button><button className="button primary" disabled={!name.trim() || members.length < 2} onClick={() => onCreate(mergeGroups(p, name.trim(), members, color).project)}><Layers size={16}/>Créer le regroupement</button></div></Modal>;
}
export function BlockDialog({ p, column, shelf, composeSize, onComposeSize, onClose, onCreate }: { p: Project; column: number; shelf: number; composeSize: { width: number; height: number }; onComposeSize: (size: { width: number; height: number }) => void; onClose: () => void; onCreate: (p: Project, blockId: string) => void }) {
  const groups = getGroups(p), [type, setType] = useState('existing'), [groupId, setGroupId] = useState(groups[0]?.id || ''), [name, setName] = useState(''), [color, setColor] = useState('#2764cf'), [members, setMembers] = useState<string[]>([]), [dimensions, setDimensions] = useState({ column, shelf, ...composeSize }), [error, setError] = useState('');
  const changeDimensions = (next: typeof dimensions) => { setDimensions(next); onComposeSize({ width: next.width, height: next.height }); setError(''); };
  const available = validBlock(p, { id: '', groupId: null, label: '', color: '', ...dimensions });
  function create() {
    let next = p, associated = groupId, label = groups.find(g => g.id === groupId)?.label || name.trim(), blockColor = groups.find(g => g.id === groupId)?.color || color;
    if (type === 'independent') { associated = ''; label = name.trim(); blockColor = color; }
    if (type === 'custom') { const merged = mergeGroups(p, name.trim(), members, color); next = merged.project; associated = merged.id; label = name.trim(); blockColor = color; }
    const block = { id: uid(), groupId: associated || null, label, color: blockColor, ...dimensions };
    if (!validBlock(next, block)) { setError('Cet emplacement est occupé ou sort du meuble. Ajustez la colonne, la tablette ou les dimensions.'); return; }
    onCreate({ ...next, blockPlacements: [...next.blockPlacements, block] }, block.id);
  }
  return <Modal title="Composer un bloc" subtitle="Choisissez son contenu et son emplacement dans le meuble." onClose={onClose}><div className="dialog-body"><div className="dialog-tabs">{[['existing', 'Groupe existant'], ['independent', 'Indépendant'], ['custom', 'Regroupement']].map(([value, label]) => <button className={type === value ? 'active' : ''} key={value} onClick={() => { setType(value); setError(''); }}>{label}</button>)}</div>{type === 'existing' ? <label className="field">Groupe associé<select value={groupId} onChange={e => setGroupId(e.target.value)}>{groups.map(g => <option value={g.id} key={g.id}>{g.label}</option>)}</select></label> : <><label className="field">Nom du bloc<input placeholder={type === 'custom' ? 'Ex. Autres marques' : 'Ex. Nouveautés'} value={name} onChange={e => setName(e.target.value)}/></label><label className="color-field"><input type="color" aria-label="Couleur du nouveau bloc" value={color} onChange={e => setColor(e.target.value)}/><span>Couleur du bloc</span></label>{type === 'custom' && <Members p={p} value={members} onChange={setMembers}/>}</>}<div className="form-grid two block-dimensions"><label>Largeur en unités<input type="number" min={1} max={capacity(p)} value={dimensions.width} onChange={e => changeDimensions({ ...dimensions, width: Number(e.target.value) })}/></label><label>Hauteur en tablettes<input type="number" min={1} max={p.shelves} value={dimensions.height} onChange={e => changeDimensions({ ...dimensions, height: Number(e.target.value) })}/></label><label>Colonne de départ<input type="number" min={1} max={capacity(p)} value={dimensions.column + 1} onChange={e => changeDimensions({ ...dimensions, column: Number(e.target.value) - 1 })}/></label><label>Tablette de départ<input type="number" min={1} max={p.shelves} value={dimensions.shelf + 1} onChange={e => changeDimensions({ ...dimensions, shelf: Number(e.target.value) - 1 })}/></label></div><div className={`capacity-note ${available ? '' : 'unavailable'}`}><Check size={14}/>{available ? `${dimensions.width * dimensions.height} cases · Emplacement disponible` : 'Emplacement occupé ou hors du meuble'}</div>{error && <div className="error-banner">{error}</div>}</div><div className="modal-footer"><button className="button" onClick={onClose}>Annuler</button><button className="button primary" disabled={!available || (type !== 'existing' && (!name.trim() || (type === 'custom' && members.length < 2)))} onClick={create}><Plus size={16}/>Ajouter le bloc</button></div></Modal>;
}
