import { useEffect, useState } from 'react';
import { FolderOpen, Plus, Copy, Trash2, Search, LoaderCircle } from 'lucide-react';
import { Modal } from './Modal';
import { deleteProject, listProjects, loadProject, saveProject } from './storage';
import { dateText } from './format';
import { uid } from './domain';
import type { Project, SavedPlan } from './types';
export function LibraryDialog({ onClose, onLoad, onNew, currentId }: { onClose: () => void; onLoad: (p: Project) => void; onNew: () => void; currentId: string }) {
  const [plans, setPlans] = useState<SavedPlan[]>([]), [search, setSearch] = useState(''), [busy, setBusy] = useState(true), [error, setError] = useState(''), [deleting, setDeleting] = useState<string | null>(null);
  const refresh = async () => { setBusy(true); try { setPlans(await listProjects()); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  useEffect(() => { void refresh(); }, []);
  const load = async (id: string) => { try { onLoad(await loadProject(id)); } catch (e) { setError((e as Error).message); } };
  const duplicate = async (id: string) => { try { const p = await loadProject(id); const copy = { ...p, id: uid(), name: `${p.name} — Copie`, updatedAt: new Date().toISOString() }; await saveProject(copy); await refresh(); } catch (e) { setError((e as Error).message); } };
  const remove = async (id: string) => { try { await deleteProject(id); setDeleting(null); await refresh(); } catch (e) { setError((e as Error).message); } };
  return <Modal title="Mes plans" subtitle="Votre bibliothèque locale, disponible même sans connexion." onClose={onClose} wide><div className="library-toolbar"><div className="search-field"><Search size={17}/><input placeholder="Rechercher un plan…" value={search} onChange={e => setSearch(e.target.value)}/></div><button className="button primary" onClick={onNew}><Plus size={17}/>Nouveau plan</button></div><div className="library-list">{busy ? <div className="empty-small"><LoaderCircle className="spin"/></div> : plans.filter(p => p.name.toLowerCase().includes(search.toLowerCase())).map(p => <div className="library-card" key={p.id}><button className="library-open" onClick={() => void load(p.id)}><div className="plan-thumbnail"><FolderOpen size={25}/><div className="mini-shelves"><i/><i/><i/></div></div><div><strong>{p.name}</strong><span>Modifié le {dateText(p.updatedAt)}</span>{p.id === currentId && <em>Plan ouvert</em>}</div></button><div className="library-actions"><button className="icon-button" title="Dupliquer ce plan" onClick={() => void duplicate(p.id)}><Copy size={17}/></button>{p.id !== currentId && <button className="icon-button danger" title="Supprimer ce plan" onClick={() => setDeleting(p.id)}><Trash2 size={17}/></button>}</div>{deleting === p.id && <div className="inline-confirm"><span>Supprimer définitivement ce plan ?</span><button className="text-button" onClick={() => setDeleting(null)}>Annuler</button><button className="button danger" onClick={() => void remove(p.id)}>Supprimer</button></div>}</div>)}{!busy && !plans.length && <div className="empty-small"><FolderOpen size={32}/><h3>Votre premier plan vous attend</h3><p>Les plans sont enregistrés automatiquement ici.</p></div>}</div>{error && <div className="error-banner">{error}</div>}<div className="modal-footer"><span className="muted">Enregistrés sur cet ordinateur</span><button className="button" onClick={onClose}>Fermer</button></div></Modal>;
}
